/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test;

import com.google.gson.FieldNamingPolicy;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.inject.Guice;
import com.google.inject.Injector;
import gradle.test.intercept.LogginModule;

import java.util.Arrays;

import static spark.Spark.get;
import static spark.Spark.notFound;

public class App {

    public static void main(String[] args) {

        Injector injector = Guice.createInjector(new LogginModule());

        Gson gson = new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
                .create();

        get("/say_my_name", (req, res) -> {
            Pessoa pessoa = new Pessoa();
            pessoa.setNome("Marcelo");
            pessoa.setSobrenome("Ortiz");
            pessoa.setNomeSocial("Heisenberg");
            Endereco endereco = new Endereco();
            endereco.setRua("Rua Sobe Desce Abc");
            endereco.setBairro("Jd. Joao Kleber");
            pessoa.setEnderecos(Arrays.asList(endereco));
            return pessoa;
        }, gson::toJson);

        notFound((req, res) -> {
            res.type("application/json");
            return "{\"message\":\"Not found\"}";
        });
    }

}
